name: Download & Convert DustinWin release JSON -> Loon rule lists

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 20 * * *'  # daily at 20:00 UTC, 按需修改或删除

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      API_TAG: sing-box-ruleset
      API_OWNER: DustinWin
      API_REPO: ruleset_geodata
      OUT_REPO: https://github.com/seeson/Custom_Loon_Rules
      AUTHOR_NAME: SeesoN
      # 本地时区（已改为上海）
      LOCALE_TZ: Asia/Shanghai
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl git

      - name: Download release JSONs and convert
        run: |
          set -euo pipefail

          OUT_DIR="loon/rules"
          mkdir -p "${OUT_DIR}"
          API_URL="https://api.github.com/repos/${API_OWNER}/${API_REPO}/releases/tags/${API_TAG}"

          echo "Fetching release info for ${API_OWNER}/${API_REPO} tag ${API_TAG} ..."
          RESP=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${GITHUB_TOKEN}" "${API_URL}")

          mapfile -t ASSETS < <(echo "$RESP" | jq -r '.assets[] | select(.name|endswith(".json")) | .browser_download_url + " " + .name')

          if [ ${#ASSETS[@]} -eq 0 ]; then
            echo "No JSON assets found in release ${API_TAG}."
            exit 0
          fi

          for entry in "${ASSETS[@]}"; do
            url=$(echo "$entry" | awk '{print $1}')
            name=$(echo "$entry" | awk '{print $2}')
            base="${name%.json}"
            echo "-------------------------------------------------------"
            echo "Processing asset: $name"
            tmpfile="$(mktemp)"
            curl -L -s -H "Authorization: token ${GITHUB_TOKEN}" "$url" -o "$tmpfile"

            # 计算：同时检查顶层和 rules[] 下的数组（兼容两种结构）
            domain_count=$(jq '[ (.domain[]? // empty), (.rules[]?.domain[]? // empty) ] | length' "$tmpfile")
            suffix_count=$(jq '[ (.domain_suffix[]? // empty), (.rules[]?.domain_suffix[]? // empty) ] | length' "$tmpfile")
            keyword_count=$(jq '[ (.domain_keyword[]? // empty), (.rules[]?.domain_keyword[]? // empty) ] | length' "$tmpfile")
            ip_total=$(jq '[ (.ip_cidr[]? // empty), (.rules[]?.ip_cidr[]? // empty) ] | length' "$tmpfile")
            total=$((domain_count + suffix_count + keyword_count + ip_total))

            # 使用上海时区时间戳（用于文件头）
            updated="$(TZ="${LOCALE_TZ}" date +'%Y-%m-%d %H:%M:%S %Z')"

            outfile="${OUT_DIR}/${base}.list"
            {
              echo "# NAME: ${base}"
              echo "# AUTHOR: ${AUTHOR_NAME}"
              echo "# REPO: ${OUT_REPO}"
              echo "# UPDATED: ${updated}"

              if [ "$domain_count" -gt 0 ]; then
                echo "# DOMAIN: ${domain_count}"
              fi
              if [ "$keyword_count" -gt 0 ]; then
                echo "# DOMAIN-KEYWORD: ${keyword_count}"
              fi
              if [ "$suffix_count" -gt 0 ]; then
                echo "# DOMAIN-SUFFIX: ${suffix_count}"
              fi
              if [ "$ip_total" -gt 0 ]; then
                echo "# IP-CIDR: ${ip_total}"
              fi

              echo "# TOTAL: ${total}"
              echo

              # 输出项：同时从顶层和 rules[] 获取，去掉空行
              # 1) DOMAIN
              jq -r '(.domain[]? , .rules[]?.domain[]?) | select(.)' "$tmpfile" | sed '/^$/d' | while IFS= read -r v; do
                printf 'DOMAIN,%s\n' "$v"
              done

              # 2) DOMAIN-SUFFIX
              jq -r '(.domain_suffix[]? , .rules[]?.domain_suffix[]?) | select(.)' "$tmpfile" | sed '/^$/d' | while IFS= read -r v; do
                printf 'DOMAIN-SUFFIX,%s\n' "$v"
              done

              # 3) DOMAIN-KEYWORD
              jq -r '(.domain_keyword[]? , .rules[]?.domain_keyword[]?) | select(.)' "$tmpfile" | sed '/^$/d' | while IFS= read -r v; do
                printf 'DOMAIN-KEYWORD,%s\n' "$v"
              done

              # 4) IPs: IPv6 -> IP-CIDR6, IPv4 -> IP-CIDR
              jq -r '(.ip_cidr[]? , .rules[]?.ip_cidr[]?) | select(.)' "$tmpfile" | sed '/^$/d' | while IFS= read -r v; do
                if [[ "$v" == *:* ]]; then
                  printf 'IP-CIDR6,%s\n' "$v"
                else
                  printf 'IP-CIDR,%s\n' "$v"
                fi
              done
            } > "$outfile"

            rm -f "$tmpfile"
            echo "Wrote $outfile (DOMAIN:${domain_count} SUFFIX:${suffix_count} KEYWORD:${keyword_count} IPS:${ip_total})"
          done

      - name: Commit converted rules if changed (commit message = 上海时间)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add loon/rules || true

          # 生成上海时区的提交信息，格式： "更新时间: 2025-09-12 20:12:29 CST"
          COMMIT_TIME="$(TZ="${LOCALE_TZ}" date +'%Y-%m-%d %H:%M:%S %Z')"
          COMMIT_MESSAGE="Updated on: ${COMMIT_TIME}"
          echo "Commit message will be: ${COMMIT_MESSAGE}"

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "${COMMIT_MESSAGE}" || true
            git push
          fi
