name: Update Classical Lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 每天23:00 UTC，即北京时间07:00

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REPO_URL: https://github.com/seeson/Custom_Loon_Rules
      AUTHOR: SeesoN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq git

      - name: Prepare folders
        run: |
          mkdir -p geo/geosite
          mkdir -p geo/geoip

      - name: Download and process lists
        run: |
          process_dir() {
              LOCAL_DIR=$1
              REMOTE_DIR=$2
              BASE_URL="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/$REMOTE_DIR"
              FILES=$(curl -s https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/$REMOTE_DIR?ref=meta | jq -r '.[] | select(.name|endswith(".list")) | .name')
              
              for file in $FILES; do
                curl -s $BASE_URL/$file -o "$LOCAL_DIR/$file"
                NAME=${file%.list}
            
                # 统计规则数量
                TOTAL=$(grep -vE '^\s*#|^\s*$' "$LOCAL_DIR/$file" | wc -l)
                DOMAIN=$(grep -cE '^DOMAIN,' "$LOCAL_DIR/$file" || echo "0")
                DOMAIN_KEYWORD=$(grep -cE '^DOMAIN-KEYWORD,' "$LOCAL_DIR/$file" || echo "0")
                DOMAIN_SUFFIX=$(grep -cE '^DOMAIN-SUFFIX,' "$LOCAL_DIR/$file" || echo "0")
                IP_CIDR=$(grep -cE '^IP-CIDR,' "$LOCAL_DIR/$file" || echo "0")
                UPDATED=$(date '+%Y-%m-%d %H:%M:%S')
            
                # 构建注释
                {
                  echo "# NAME: $NAME"
                  echo "# AUTHOR: $AUTHOR"
                  echo "# REPO: $REPO_URL"
                  echo "# UPDATED: $UPDATED"
                  echo "# TOTAL: $TOTAL"
                  [ "$DOMAIN" -gt 0 ] && echo "# DOMAIN: $DOMAIN"
                  [ "$DOMAIN_KEYWORD" -gt 0 ] && echo "# DOMAIN-KEYWORD: $DOMAIN_KEYWORD"
                  [ "$DOMAIN_SUFFIX" -gt 0 ] && echo "# DOMAIN-SUFFIX: $DOMAIN_SUFFIX"
                  [ "$IP_CIDR" -gt 0 ] && echo "# IP-CIDR: $IP_CIDR"
                  echo ""
                } > header.tmp
            
                cat header.tmp "$LOCAL_DIR/$file" > temp
                echo "" >> temp
                mv temp "$LOCAL_DIR/$file"
                rm -f header.tmp
              done
          }

            # 处理 geo/geosite
            process_dir geo/geosite geo/geosite/classical
            # 处理 geo/geoip
            process_dir geo/geoip geo/geoip/classical

      - name: Commit and push changes
        run: |
          git config user.name "$AUTHOR"
          git config user.email "actions@github.com"
          git add geo/
          UPDATED=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Released on $UPDATED" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin main
