name: Update Classical Lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 每天20:00 UTC, 即北京时间04:00

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REPO_URL: https://github.com/seeson/Custom_Loon_Rules
      AUTHOR: SeesoN
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq git

      - name: Prepare folders
        run: |
          mkdir -p geo/geosite
          mkdir -p geo/geoip

      - name: Download and process geo/geosite lists
        run: |
          BASE_URL="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/classical"
          FILES=$(curl -s https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/geo/geosite/classical?ref=meta | jq -r '.[] | select(.name|endswith(".list")) | .name')
          for file in $FILES; do
            curl -s $BASE_URL/$file -o geo/geosite/$file
            NAME=${file%.list}
            # 统计规则数量
            TOTAL=$(grep -vE '^\s*#|^\s*$' geo/geosite/$file | wc -l)
            DOMAIN=$(grep -cE '^DOMAIN,' geo/geosite/$file || echo "")
            DOMAIN_KEYWORD=$(grep -cE '^DOMAIN-KEYWORD,' geo/geosite/$file || echo "")
            DOMAIN_SUFFIX=$(grep -cE '^DOMAIN-SUFFIX,' geo/geosite/$file || echo "")
            IP_CIDR=$(grep -cE '^IP-CIDR,' geo/geosite/$file || echo "")
            # 更新时间
            UPDATED=$(date '+%Y-%m-%d %H:%M:%S')
            # 添加注释
            sed -i "1i# NAME: $NAME\n# AUTHOR: $AUTHOR\n# REPO: $REPO_URL\n# UPDATED: $UPDATED\n# DOMAIN: $DOMAIN\n# DOMAIN-KEYWORD: $DOMAIN_KEYWORD\n# DOMAIN-SUFFIX: $DOMAIN_SUFFIX\n# IP-CIDR: $IP_CIDR\n# TOTAL: $TOTAL" geo/geosite/$file
          done

      - name: Download and process geo/geoip lists
        run: |
          BASE_URL="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/classical"
          FILES=$(curl -s https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/geo/geoip/classical?ref=meta | jq -r '.[] | select(.name|endswith(".list")) | .name')
          for file in $FILES; do
            curl -s $BASE_URL/$file -o geo/geoip/$file
            NAME=${file%.list}
            # 统计规则数量
            TOTAL=$(grep -vE '^\s*#|^\s*$' geo/geoip/$file | wc -l)
            DOMAIN=$(grep -cE '^DOMAIN,' geo/geoip/$file || echo "")
            DOMAIN_KEYWORD=$(grep -cE '^DOMAIN-KEYWORD,' geo/geoip/$file || echo "")
            DOMAIN_SUFFIX=$(grep -cE '^DOMAIN-SUFFIX,' geo/geoip/$file || echo "")
            IP_CIDR=$(grep -cE '^IP-CIDR,' geo/geoip/$file || echo "")
            UPDATED=$(date '+%Y-%m-%d %H:%M:%S')
            sed -i "1i# NAME: $NAME\n# AUTHOR: $AUTHOR\n# REPO: $REPO_URL\n# UPDATED: $UPDATED\n# DOMAIN: $DOMAIN\n# DOMAIN-KEYWORD: $DOMAIN_KEYWORD\n# DOMAIN-SUFFIX: $DOMAIN_SUFFIX\n# IP-CIDR: $IP_CIDR\n# TOTAL: $TOTAL" geo/geoip/$file
          done

      - name: Commit and push changes
        run: |
          git config user.name "$AUTHOR"
          git config user.email "actions@github.com"
          git add geo/
          UPDATED=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Released on $UPDATED" || echo "No changes to commit"
          git push
